export const SET_USERS = "SET_USERS";
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const LOGOUT = "LOGOUT";
export const SET_UN_ANSWERED_QUESTIONS = "SET_UN_ANSWERED_QUESTIONS";
export const SET_ANSWERED_QUESTIONS = "SET_ANSWERED_QUESTIONS";
export const SET_QUESTIONS = "SET_QUESTIONS";
